<?php
/**
 * JSCFR Theme Code Generator — generates ready-to-use PHP snippets
 * for retrieving and displaying custom field values in theme templates.
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

if ( ! class_exists( 'JSCFR_Theme_Code' ) ) {

    final class JSCFR_Theme_Code {

        private static $instance = null;

        public static function get_instance() {
            if ( null === self::$instance ) {
                self::$instance = new self();
            }
            return self::$instance;
        }

        private function __construct() {
            add_action( 'wp_ajax_jscfr_generate_theme_code', array( $this, 'ajax_generate_theme_code' ) );
        }

        /* ---------------------------------------------------------- */
        /*  AJAX handler                                               */
        /* ---------------------------------------------------------- */

        /**
         * Generate theme template code for a field group.
         */
        public function ajax_generate_theme_code() {
            check_ajax_referer( JSCFR_BUILDER_NONCE, 'nonce' );

            if ( ! current_user_can( 'manage_options' ) ) {
                wp_send_json_error( array( 'message' => __( 'Permission denied.', 'jscfr' ) ) );
            }

            $fg_id = isset( $_POST['fg_id'] ) ? sanitize_text_field( wp_unslash( $_POST['fg_id'] ) ) : '';

            if ( empty( $fg_id ) ) {
                wp_send_json_error( array( 'message' => __( 'Missing field group ID.', 'jscfr' ) ) );
            }

            $fg = JSCFR_Plugin::get_field_group( $fg_id );

            if ( ! $fg ) {
                wp_send_json_error( array( 'message' => __( 'Field group not found.', 'jscfr' ) ) );
            }

            $code = $this->jscfr_generate_code( $fg );

            wp_send_json_success( array( 'code' => $code ) );
        }

        /* ---------------------------------------------------------- */
        /*  Code generation                                            */
        /* ---------------------------------------------------------- */

        /**
         * Build the full PHP snippet for a field group.
         *
         * @param array $fg Field group configuration.
         * @return string Generated PHP code.
         */
        private function jscfr_generate_code( $fg ) {
            $title = isset( $fg['title'] ) ? $fg['title'] : 'Untitled';
            $tabs  = isset( $fg['tabs'] ) ? $fg['tabs'] : array();

            $lines   = array();
            $lines[] = '<?php';
            $lines[] = '/**';
            $lines[] = ' * Template code for: ' . $title;
            $lines[] = ' * Generated by JSCFR Theme Code Generator';
            $lines[] = ' */';
            $lines[] = '';

            foreach ( $tabs as $tab ) {
                $tab_label = isset( $tab['label'] ) ? $tab['label'] : '';
                $groups    = isset( $tab['groups'] ) ? $tab['groups'] : array();

                if ( ! empty( $tab_label ) && count( $tabs ) > 1 ) {
                    $lines[] = '// === Tab: ' . $tab_label . ' ===';
                    $lines[] = '';
                }

                foreach ( $groups as $group ) {
                    $group_name   = isset( $group['name'] ) ? $group['name'] : '';
                    $group_label  = isset( $group['label'] ) ? $group['label'] : $group_name;
                    $group_fields = isset( $group['fields'] ) ? $group['fields'] : array();

                    if ( empty( $group_fields ) ) {
                        continue;
                    }

                    $lines[] = '// ' . $group_label . ' (Repeater)';
                    $lines[] = 'if ( jscfr_have_rows( \'' . $this->jscfr_escape_single( $group_name ) . '\' ) ) {';
                    $lines[] = '    while ( jscfr_the_row() ) {';

                    foreach ( $group_fields as $field ) {
                        $field_lines = $this->jscfr_generate_field_code( $field, true );
                        foreach ( $field_lines as $fl ) {
                            $lines[] = '        ' . $fl;
                        }
                    }

                    $lines[] = '    }';
                    $lines[] = '}';
                    $lines[] = '';
                }
            }

            return implode( "\n", $lines );
        }

        /**
         * Generate code lines for a single field.
         *
         * @param array $field     Field configuration.
         * @param bool  $is_sub    Whether this field is inside a repeater row.
         * @return array Lines of PHP code (without leading indentation).
         */
        private function jscfr_generate_field_code( $field, $is_sub = false ) {
            $name  = isset( $field['name'] ) ? $field['name'] : '';
            $type  = isset( $field['type'] ) ? $field['type'] : 'text';
            $label = isset( $field['label'] ) ? $field['label'] : $name;

            $safe_name = $this->jscfr_escape_single( $name );
            $var_name  = '$' . preg_replace( '/[^a-zA-Z0-9_]/', '_', $name );

            // Display-only field types — skip code generation.
            if ( in_array( $type, array( 'heading', 'divider', 'button' ), true ) ) {
                return array( '// ' . $label . ' — display-only field, no data to retrieve.' );
            }

            $getter = $is_sub
                ? "jscfr_get_sub_field( '{$safe_name}' )"
                : "jscfr_get_field( '{$safe_name}' )";

            $lines = array();
            $lines[] = '';
            $lines[] = '// ' . $label . ' (' . $type . ')';

            switch ( $type ) {

                /* -------------------------------------------------- */
                /*  Plain text / scalar types                          */
                /* -------------------------------------------------- */
                case 'text':
                case 'textarea':
                case 'email':
                case 'url':
                case 'password':
                case 'number':
                case 'range':
                case 'hidden':
                case 'color':
                case 'date':
                case 'datetime':
                case 'time':
                    $lines[] = $var_name . ' = ' . $getter . ';';
                    $lines[] = 'echo esc_html( ' . $var_name . ' );';
                    break;

                /* -------------------------------------------------- */
                /*  Rich / HTML content                                */
                /* -------------------------------------------------- */
                case 'wysiwyg':
                case 'message':
                case 'custom_html':
                    $lines[] = $var_name . ' = ' . $getter . ';';
                    $lines[] = 'echo wp_kses_post( ' . $var_name . ' );';
                    break;

                /* -------------------------------------------------- */
                /*  Single image (returns <img> via helper)            */
                /* -------------------------------------------------- */
                case 'image':
                case 'single_image':
                case 'image_upload':
                    if ( $is_sub ) {
                        // Inside a repeater — fall back to attachment ID approach.
                        $lines[] = $var_name . ' = ' . $getter . ';';
                        $lines[] = 'if ( ' . $var_name . ' ) {';
                        $lines[] = '    echo wp_get_attachment_image( ' . $var_name . ', \'full\' );';
                        $lines[] = '}';
                    } else {
                        $lines[] = 'echo jscfr_get_image( \'' . $safe_name . '\', false, \'full\' );';
                    }
                    break;

                /* -------------------------------------------------- */
                /*  File / video (attachment ID → URL)                 */
                /* -------------------------------------------------- */
                case 'file':
                case 'file_upload':
                case 'file_input':
                case 'video':
                    $lines[] = $var_name . ' = ' . $getter . ';';
                    $lines[] = 'if ( ' . $var_name . ' ) {';
                    $lines[] = '    $url = wp_get_attachment_url( ' . $var_name . ' );';
                    $lines[] = '    echo \'<a href="\' . esc_url( $url ) . \'">\' . esc_html( basename( $url ) ) . \'</a>\';';
                    $lines[] = '}';
                    break;

                /* -------------------------------------------------- */
                /*  Gallery / Image Advanced (array of IDs)            */
                /* -------------------------------------------------- */
                case 'gallery':
                case 'image_advanced':
                    $lines[] = $var_name . ' = ' . $getter . ';';
                    $lines[] = 'if ( ! empty( ' . $var_name . ' ) && is_array( ' . $var_name . ' ) ) {';
                    $lines[] = '    foreach ( ' . $var_name . ' as $image_id ) {';
                    $lines[] = '        echo wp_get_attachment_image( $image_id, \'full\' );';
                    $lines[] = '    }';
                    $lines[] = '}';
                    break;

                /* -------------------------------------------------- */
                /*  File Advanced (array of IDs → URLs)                */
                /* -------------------------------------------------- */
                case 'file_advanced':
                    $lines[] = $var_name . ' = ' . $getter . ';';
                    $lines[] = 'if ( ! empty( ' . $var_name . ' ) && is_array( ' . $var_name . ' ) ) {';
                    $lines[] = '    foreach ( ' . $var_name . ' as $file_id ) {';
                    $lines[] = '        $url = wp_get_attachment_url( $file_id );';
                    $lines[] = '        echo \'<a href="\' . esc_url( $url ) . \'">\' . esc_html( basename( $url ) ) . \'</a>\';';
                    $lines[] = '    }';
                    $lines[] = '}';
                    break;

                /* -------------------------------------------------- */
                /*  Select-style fields                                */
                /* -------------------------------------------------- */
                case 'select':
                case 'radio':
                case 'button_group':
                case 'checkbox':
                case 'true_false':
                case 'switch':
                case 'sidebar':
                case 'slider':
                case 'autocomplete':
                case 'select_advanced':
                case 'image_select':
                    $lines[] = $var_name . ' = ' . $getter . ';';
                    $lines[] = 'echo esc_html( ' . $var_name . ' );';
                    break;

                /* -------------------------------------------------- */
                /*  Link (array with url, title, target)               */
                /* -------------------------------------------------- */
                case 'link':
                    $lines[] = $var_name . ' = ' . $getter . ';';
                    $lines[] = 'if ( ! empty( ' . $var_name . ' ) && is_array( ' . $var_name . ' ) ) {';
                    $lines[] = '    $url    = isset( ' . $var_name . '[\'url\'] ) ? ' . $var_name . '[\'url\'] : \'\';';
                    $lines[] = '    $title  = isset( ' . $var_name . '[\'title\'] ) ? ' . $var_name . '[\'title\'] : \'\';';
                    $lines[] = '    $target = isset( ' . $var_name . '[\'target\'] ) ? ' . $var_name . '[\'target\'] : \'_self\';';
                    $lines[] = '    echo \'<a href="\' . esc_url( $url ) . \'" target="\' . esc_attr( $target ) . \'">\' . esc_html( $title ) . \'</a>\';';
                    $lines[] = '}';
                    break;

                /* -------------------------------------------------- */
                /*  oEmbed                                             */
                /* -------------------------------------------------- */
                case 'oembed':
                    $lines[] = $var_name . ' = ' . $getter . ';';
                    $lines[] = 'if ( ' . $var_name . ' ) {';
                    $lines[] = '    echo wp_oembed_get( ' . $var_name . ' );';
                    $lines[] = '}';
                    break;

                /* -------------------------------------------------- */
                /*  Post Object                                        */
                /* -------------------------------------------------- */
                case 'post_object':
                    $lines[] = $var_name . ' = ' . $getter . ';';
                    $lines[] = 'if ( ' . $var_name . ' ) {';
                    $lines[] = '    $post_obj = get_post( ' . $var_name . ' );';
                    $lines[] = '    if ( $post_obj ) {';
                    $lines[] = '        echo esc_html( $post_obj->post_title );';
                    $lines[] = '    }';
                    $lines[] = '}';
                    break;

                /* -------------------------------------------------- */
                /*  Relationship (array of post IDs)                   */
                /* -------------------------------------------------- */
                case 'relationship':
                    $lines[] = $var_name . ' = ' . $getter . ';';
                    $lines[] = 'if ( ! empty( ' . $var_name . ' ) && is_array( ' . $var_name . ' ) ) {';
                    $lines[] = '    foreach ( ' . $var_name . ' as $post_id ) {';
                    $lines[] = '        $post_obj = get_post( $post_id );';
                    $lines[] = '        if ( $post_obj ) {';
                    $lines[] = '            echo esc_html( $post_obj->post_title ) . \'<br>\';';
                    $lines[] = '        }';
                    $lines[] = '    }';
                    $lines[] = '}';
                    break;

                /* -------------------------------------------------- */
                /*  Taxonomy / Taxonomy Advanced                       */
                /* -------------------------------------------------- */
                case 'taxonomy':
                case 'taxonomy_advanced':
                    $lines[] = $var_name . ' = ' . $getter . ';';
                    $lines[] = 'if ( ' . $var_name . ' ) {';
                    $lines[] = '    $term = get_term( ' . $var_name . ' );';
                    $lines[] = '    if ( $term && ! is_wp_error( $term ) ) {';
                    $lines[] = '        echo esc_html( $term->name );';
                    $lines[] = '    }';
                    $lines[] = '}';
                    break;

                /* -------------------------------------------------- */
                /*  User                                               */
                /* -------------------------------------------------- */
                case 'user':
                    $lines[] = $var_name . ' = ' . $getter . ';';
                    $lines[] = 'if ( ' . $var_name . ' ) {';
                    $lines[] = '    $user = get_user_by( \'ID\', ' . $var_name . ' );';
                    $lines[] = '    if ( $user ) {';
                    $lines[] = '        echo esc_html( $user->display_name );';
                    $lines[] = '    }';
                    $lines[] = '}';
                    break;

                /* -------------------------------------------------- */
                /*  Key Value (array of key-value pairs)               */
                /* -------------------------------------------------- */
                case 'key_value':
                    $lines[] = $var_name . ' = ' . $getter . ';';
                    $lines[] = 'if ( ! empty( ' . $var_name . ' ) && is_array( ' . $var_name . ' ) ) {';
                    $lines[] = '    foreach ( ' . $var_name . ' as $pair ) {';
                    $lines[] = '        $key   = isset( $pair[\'key\'] ) ? $pair[\'key\'] : \'\';';
                    $lines[] = '        $value = isset( $pair[\'value\'] ) ? $pair[\'value\'] : \'\';';
                    $lines[] = '        echo esc_html( $key ) . \': \' . esc_html( $value ) . \'<br>\';';
                    $lines[] = '    }';
                    $lines[] = '}';
                    break;

                /* -------------------------------------------------- */
                /*  Fieldset Text / Text List (array)                  */
                /* -------------------------------------------------- */
                case 'fieldset_text':
                case 'text_list':
                    $lines[] = $var_name . ' = ' . $getter . ';';
                    $lines[] = 'if ( ! empty( ' . $var_name . ' ) && is_array( ' . $var_name . ' ) ) {';
                    $lines[] = '    foreach ( ' . $var_name . ' as $key => $value ) {';
                    $lines[] = '        echo esc_html( $key ) . \': \' . esc_html( $value ) . \'<br>\';';
                    $lines[] = '    }';
                    $lines[] = '}';
                    break;

                /* -------------------------------------------------- */
                /*  Icon                                               */
                /* -------------------------------------------------- */
                case 'icon':
                    $lines[] = $var_name . ' = ' . $getter . ';';
                    $lines[] = 'if ( ' . $var_name . ' ) {';
                    $lines[] = '    if ( strpos( ' . $var_name . ', \'svg:\' ) === 0 ) {';
                    $lines[] = '        echo wp_kses( substr( ' . $var_name . ', 4 ), JSCFR_Metabox::svg_allowed_tags() );';
                    $lines[] = '    } else {';
                    $lines[] = '        echo \'<span class="\' . esc_attr( ' . $var_name . ' ) . \'"></span>\';';
                    $lines[] = '    }';
                    $lines[] = '}';
                    break;

                /* -------------------------------------------------- */
                /*  Google Map / OpenStreetMap                          */
                /* -------------------------------------------------- */
                case 'google_map':
                case 'osm':
                    $lines[] = $var_name . ' = ' . $getter . ';';
                    $lines[] = 'if ( ! empty( ' . $var_name . ' ) && is_array( ' . $var_name . ' ) ) {';
                    $lines[] = '    $lat     = isset( ' . $var_name . '[\'lat\'] ) ? ' . $var_name . '[\'lat\'] : \'\';';
                    $lines[] = '    $lng     = isset( ' . $var_name . '[\'lng\'] ) ? ' . $var_name . '[\'lng\'] : \'\';';
                    $lines[] = '    $zoom    = isset( ' . $var_name . '[\'zoom\'] ) ? ' . $var_name . '[\'zoom\'] : 14;';
                    $lines[] = '    $address = isset( ' . $var_name . '[\'address\'] ) ? ' . $var_name . '[\'address\'] : \'\';';
                    $lines[] = '    echo esc_html( $address ) . \' (\' . esc_html( $lat ) . \', \' . esc_html( $lng ) . \')\';';
                    $lines[] = '}';
                    break;

                /* -------------------------------------------------- */
                /*  Background                                         */
                /* -------------------------------------------------- */
                case 'background':
                    $lines[] = $var_name . ' = ' . $getter . ';';
                    $lines[] = 'if ( ! empty( ' . $var_name . ' ) && is_array( ' . $var_name . ' ) ) {';
                    $lines[] = '    $bg_color      = isset( ' . $var_name . '[\'color\'] ) ? ' . $var_name . '[\'color\'] : \'\';';
                    $lines[] = '    $bg_image      = isset( ' . $var_name . '[\'image\'] ) ? ' . $var_name . '[\'image\'] : \'\';';
                    $lines[] = '    $bg_repeat     = isset( ' . $var_name . '[\'repeat\'] ) ? ' . $var_name . '[\'repeat\'] : \'\';';
                    $lines[] = '    $bg_position   = isset( ' . $var_name . '[\'position\'] ) ? ' . $var_name . '[\'position\'] : \'\';';
                    $lines[] = '    $bg_size       = isset( ' . $var_name . '[\'size\'] ) ? ' . $var_name . '[\'size\'] : \'\';';
                    $lines[] = '    $bg_attachment = isset( ' . $var_name . '[\'attachment\'] ) ? ' . $var_name . '[\'attachment\'] : \'\';';
                    $lines[] = '    $style = \'\';';
                    $lines[] = '    if ( $bg_color ) { $style .= \'background-color:\' . esc_attr( $bg_color ) . \';\'; }';
                    $lines[] = '    if ( $bg_image ) { $style .= \'background-image:url(\' . esc_url( $bg_image ) . \');\'; }';
                    $lines[] = '    if ( $bg_repeat ) { $style .= \'background-repeat:\' . esc_attr( $bg_repeat ) . \';\'; }';
                    $lines[] = '    if ( $bg_position ) { $style .= \'background-position:\' . esc_attr( $bg_position ) . \';\'; }';
                    $lines[] = '    if ( $bg_size ) { $style .= \'background-size:\' . esc_attr( $bg_size ) . \';\'; }';
                    $lines[] = '    if ( $bg_attachment ) { $style .= \'background-attachment:\' . esc_attr( $bg_attachment ) . \';\'; }';
                    $lines[] = '    echo \'<div style="\' . $style . \'"></div>\';';
                    $lines[] = '}';
                    break;

                /* -------------------------------------------------- */
                /*  Fallback for unknown types                         */
                /* -------------------------------------------------- */
                default:
                    $lines[] = $var_name . ' = ' . $getter . ';';
                    $lines[] = 'echo esc_html( ' . $var_name . ' );';
                    break;
            }

            return $lines;
        }

        /* ---------------------------------------------------------- */
        /*  Helpers                                                    */
        /* ---------------------------------------------------------- */

        /**
         * Escape a string for safe inclusion inside single-quoted PHP strings.
         *
         * @param string $str Input string.
         * @return string Escaped string.
         */
        private function jscfr_escape_single( $str ) {
            return str_replace( array( '\\', '\'' ), array( '\\\\', '\\\'' ), $str );
        }
    }

}
